set nobackup noswapfile
set scrolloff=1 list listchars=tab:»\ ,trail:·
set splitbelow splitright statusline=\ %f\ %y\ %m\ %r%=(%c,\ %l)\ 
set ruler cursorline shortmess=atI foldmethod=marker foldlevelstart=10
set autoindent cindent expandtab tabstop=2 shiftwidth=2 wildmode=list:longest
set timeout timeoutlen=1000 ttimeoutlen=100
" set colorcolumn=80,100 number
syntax on
colorscheme u
let mapleader=" "
tmap <C-w> <C-\><C-n><C-w>
tnoremap <Esc> <C-\><C-n>
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
inoremap <tab> <C-n>
nmap - :edit %:h<CR>
nmap <leader><leader> :nohlsearch<CR>
autocmd VimResized * :wincmd =
autocmd CompleteDone * silent! pclose
autocmd BufRead,BufNewFile *.tmpl set filetype=html
autocmd BufRead,BufNewFile *.go set filetype=go
autocmd BufRead,BufNewFile *.md set filetype=markdown
autocmd BufRead,BufNewFile *.sol set filetype=solidity

call plug#begin()
Plug 'w0rp/ale'
Plug 'editorconfig/editorconfig-vim'
call plug#end()

set grepprg=ag\ --nogroup\ --nocolor
let g:netrw_banner = 0
let g:netrw_browse_split = 0
let g:netrw_list_hide = '^\.\.\=/\=$,\.DS_Store,.git\/$'
autocmd FileType netrw set nolist
let g:ale_fix_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_fixers = {'javascript':['prettier'],'javascriptreact':['prettier'],'typescript':['prettier'],'go':['goimports'],'dart':['dartfmt'],'cpp':['clang-format'],'rust':['rustfmt']}
let g:ale_linters = {'javascript':['eslint'],'javascriptreact':['eslint'],'go':['gofmt','golint','go vet','go build'],'dart':['language_server'],'cpp':['gcc']}
