set nobackup noswapfile
set scrolloff=1 colorcolumn=80,100 list listchars=tab:»\ ,trail:·
set splitbelow splitright statusline=\ %f\ %y\ %m\ %r%=(%c,\ %l)\ 
set number ruler cursorline shortmess=atI foldmethod=marker foldlevelstart=10
set lisp autoindent cindent expandtab tabstop=2 shiftwidth=2 wildmode=list:longest
set timeout timeoutlen=1000 ttimeoutlen=100
syntax on
colorscheme u
let mapleader=" "
nmap <leader><leader> :nohlsearch<CR>
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
inoremap jj <esc>
inoremap jk <esc>
let s:uname = system("echo -n \"$(uname)\"")
if s:uname == "Darwin"
  vmap <C-x> :!pbcopy<CR>
else
  vmap <C-x> :!xclip -f -sel clip<CR>
endif
autocmd VimResized * :wincmd =
autocmd BufWinEnter *.tmpl set filetype=html
autocmd BufRead,BufNewFile *.go set filetype=go
autocmd BufRead,BufNewFile *.md set filetype=markdown
autocmd BufRead,BufNewFile *.dart set filetype=dart

call plug#begin()
Plug 'w0rp/ale'
Plug 'tpope/vim-vinegar'
Plug 'ervandew/supertab'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'editorconfig/editorconfig-vim'
call plug#end()

set grepprg=ag\ --nogroup\ --nocolor
let g:ctrlp_use_caching = 0
let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
let g:ale_fix_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_fixers = {'javascript': ['prettier'],'javascriptreact': ['prettier'],
  \ 'go':['goimports'],
  \ 'dart':['dartfmt'],'cpp':['clang-format'],'rust':['rustfmt']}
let g:ale_linters = {'javascript':['eslint'],'javascriptreact':['eslint'],
  \ 'go':['gofmt','golint','go vet','go build'],
  \ 'dart':['language_server'],'cpp':['gcc']}
